version: "3.8"
services:
  backend:
    build: 
      context: ./backend
    ports:
      - "4000:4000"
    networks:
      - chat-net
    environment:
      - NODE_ENV=production

  frontend1:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - chat-net
    environment:
      - REACT_APP_INSTANCE=1
      - REACT_APP_BACKEND_URL=http://backend:4000

  frontend2:
    build: 
      context: ./frontend
    ports:
      - "3001:3000"
    networks:
      - chat-net
    environment:
      - REACT_APP_INSTANCE=2
      - REACT_APP_BACKEND_URL=http://backend:4000

networks:
  chat-net:
    driver: bridge
